
testURL = http://www.guvi.in/
autoURL = http://www.google.co.in/
JSURL = http://www.letskodeit.com/practice
wndURL = http://www.demoqa.com/browser-windows
loginURL = https://practicetestautomation.com/practice-test-login/
keyboardlogin = https://demoqa.com/text-box
autocompleteurl = https://www.wikipedia.org/
Mousehover = https://www.guvi.in/
RightClick = https://vinothqaacademy.com/mouse-event/
DoubleClick = https://testautomationpractice.blogspot.com/Draganddrop = https://demo.automationtesting.in/Static.html
scrollandview = https://en.wikipedia.org/wiki/List_of_national_birds
dragdrop = https://demo.automationtesting.in/Static.html
window = https://the-internet.herokuapp.com/windows
alert = https://the-internet.herokuapp.com/javascript_alerts
dateurl = https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/datepicker-dialog/
waitURL = https://www.demoblaze.com/
webtables = https://tablepress.org/demo/
singlefile = http://the-internet.herokuapp.com/upload
multiplefile = https://demo.automationtesting.in/FileUpload.html
download = https://ui.vision/demo/filedownload
Tablepages = https://tablepress.org/demo/
bootstrap = https://www.dummyticket.com/dummy-ticket-for-visa-application/
frames = https://demo.automationtesting.in/Frames.html
browserName = chrome

userName = student
password = Password123
email = arshad@htcindia.com
address = 123,NGO Colony,France 
date = August 2019


Incorrectuser = Bhavani
Incorrectpass = briyani

waituser = JDJDJD
waitpassword = lokesh